import './globals.css'
import Navbar from './nav/Navbar'
import ToasterProvider from './providers/ToasterProvider'

export const metadata = {
  title: 'Carauctions',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* here is where all our React components go */}
      <body>
        <ToasterProvider/>
        <Navbar/>
        <main className='container mx-auto px-5 pt-10'>
          {children}
        </main>
      </body>
    </html>
  )
}
